Add Debian 12 bookworm support; drop Debian 10 buster support
systemli/ansible-drift pull request #28
Opened 2023-08-06 13:57 UTC by nevart

2023-08-06 18:31 UTC, t2d requested changes
The most interesting part will be if `actionable.py` will still work with the new version of ansible in bookworm. It was already very hacky in the past. Have you tried that?

2023-08-06 18:31 UTC, t2d commented on .github/workflows/main.yml
>      uses: systemli/github-ansible-workflow/.github/workflows/ansible-integration-workflow.yaml@main
```suggestion
    uses: systemli/github-ansible-workflow/.github/workflows/ansible-integration-workflow.yaml@v1.2.0
```

2023-08-06 18:31 UTC, t2d commented on .github/workflows/main.yml
> +      distros: '[ "debian12", "debian11" ]'
```suggestion
```
this is already the default

2023-08-11 08:43 UTC, t2d commented on .github/workflows/main.yml
> +      distros: '[ "debian12", "debian11" ]'
yes :)

2023-09-13 13:38 UTC, 0x46616c6b commented
I removed the `actionable` callback plugin in #29 because it is deprecated and we can use the default callback with a specific option (already applied in #29)

2023-09-13 13:47 UTC, 0x46616c6b reviewed
It seems that the defaults are not working as expected. Without setting them explicitly here, it will be tested against Debian 10 and Debian 11.

2023-09-14 21:01 UTC, merged